engines:
  brakeman:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - ruby
    exclude_paths:
      - "app/controllers/"
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
    - "app/**"
    - "lib/**"
exclude_paths:
  - "config/"
  - "db/"
  - "public/"
  - "spec/"
  - "vendor/"