# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]

# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
ROLLBAR_ACCESS_TOKEN: b6ee2eb007644e8aa20a41de39233cc9
NEW_RELIC_LICENSE_KEY: "1372021"
SENTRY_DSN: https://a765b5d3737f4265b20b00d268f26c4f:d50deb14710c4d82ae3efd8a86ec00c9@app.getsentry.com/85449
GMAIL_USERNAME: Your_Username
GMAIL_PASSWORD: Your_Password
DOMAIN_NAME: example.com
ADMIN_NAME: First User
ADMIN_EMAIL: user@example.com
ADMIN_PASSWORD: changeme
CODECLIMATE_REPO_TOKEN: 0d4b4a4aa57751f5946ca667680d8f8dba7da8f33586aaa182f94714181d57ba
TWILIO_APP_NAME: ChatBoxApp
TWILIO_ACCOUNT_SID: AC6bdd4ebad16baa9259a477cef360e9fc
TWILIO_API_KEY: SK4a94ba666830d559e8f1707d3e7aa2c3
TWILIO_API_SECRET: GOeVAn3W6uEWb66O2HoUgtKltzff631y
TWILIO_SERVICE_SID: IS8b176fa0adb04b919e608593cd3f239e
GOOGLE_PLACE_API_KEY: AIzaSyDuBZ1g5CRiHx90bIYJSnE9-TqgsPAx6OU